apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: spilo-s1
spec:
  teamId: "spilo"
  volume:
    size: 1Gi
  numberOfInstances: 3
  users:
    # database owner
    zalando:
    - superuser
    - createdb

    # role for application foo
    foo_user:

    # new role for application bar
    bar_user:

  #databases: name->owner
  databases:
    foo: zalando
    bar: zalando
  postgresql:
    version: "10"
    parameters:
      timezone: "America/Los_Angeles"
